version: '3'
services:
  graphite:
    image: graphiteapp/graphite-statsd
    restart: always
    ports:
      - '80:80'
      - '2003-2004:2003-2004' # carbon
      - '2023-2024:2023-2024'
      - '8125:8125/udp' # statsd
      - '8126:8126'
